export const aboutData = [
  {
    f_name: "Speak",
    l_name: "Native",
    image: require(`../../images/speaknative.jpg`),
    question: `Can’t read their language?`,
    desc: `SpeakNative enables the user to communicate in their native language by the help our translator.Our TTS(Text to Speech) service reads it out loud for you.`,
    class: "",
  },
  {
    f_name: "Native",
    l_name: "Market",
    image: require("../../images/nativemarket.jpg"),
    question: `Want to connect with local vendors?`,
    desc: `NativeMarket lists local vendors with their products which are already tested for their quality.`,
    class: "aboutcard-wrapper-reverse",
  },
  {
    f_name: "Scan",
    l_name: "Monument",
    image: require("../../images/scanmonument.jpg"),
    question: `Not Interested in reading?`,
    desc: `Scan any monuments in your tourist spot and find out interesting facts about it with the help of AI powered Image Classifier.ScanMonument reads the content for you with the help of our TTS(Text to Speech) engine.`,
    class: "",
  },
  {
    f_name: "Travel",
    l_name: "Card",
    image: require("../../images/travelcard.jpg"),
    question: `Do you travel too often?`,
    desc: `Get benefits from TravelCard credit system, to redeem attractive offers throughout your next journey.`,
    class: "aboutcard-wrapper-reverse",
  },
  {
    f_name: "Suggest",
    l_name: `Plan`,
    image: require("../../images/suggestaplan.jpg"),
    question: `Ever stuck in a place wondering what to do?`,
    desc: `SuggestPlan suggests you the best route covering maximum tourist places within short time.`,
    class: "",
  },
  {
    f_name: "Locate",
    l_name: "Native",
    image: require("../../images/locatenative.jpg"),
    question: `Want to connect with local vendors?`,
    desc: `LocateNative provides you the best native essential service with respect to your location.`,
    class: "aboutcard-wrapper-reverse",
  },
];
